name: Build and Deploy Backend

on:
  push:

jobs:
  build-backend:
    uses: ./.github/workflows/build-container.yaml
    with:
      container-name: backend
      tag: latest
      context-path: backend
    secrets:
      GCP_CLOUDRUN_REGION: ${{ secrets.GCP_CLOUDRUN_REGION }}
      GAR_JSON_KEY: ${{ secrets.GAR_JSON_KEY }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}

  deploy-backend:
    needs: build-backend
    uses: ./.github/workflows/deploy-gcp.yaml
    with:
      container-name: backend
      tag: latest
    secrets:
      GCP_CLOUDRUN_REGION: ${{ secrets.GCP_CLOUDRUN_REGION }}
      GAR_JSON_KEY: ${{ secrets.GAR_JSON_KEY }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
