name: Build and Push Backend

on:
  push:

jobs:
  call-build:
    uses: vivalareda/calculator-gpa/.github/workflows/build-container.yaml@main
    with:
      container-name: backend
      tag: latest
      context-path: backend
    secrets:
      GCP_CLOUDRUN_REGION: ${{ secrets.GCP_CLOUDRUN_REGION }}
      GAR_JSON_KEY: ${{ secrets.GAR_JSON_KEY }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
