name: Build and Deploy Frontend

on:
  push:
    paths:
      - "src/**"
      - "package.json"
      - "next.config.mjs"
      - "tailwind.config.ts"
      - "tsconfig.json"
      - "Dockerfile"
    branches:
      - main

jobs:
  build-frontend:
    uses: ./.github/workflows/build-container.yaml
    with:
      container-name: frontend
      tag: latest
      context-path: .
    secrets:
      GCP_CLOUDRUN_REGION: ${{ secrets.GCP_CLOUDRUN_REGION }}
      GAR_JSON_KEY: ${{ secrets.GAR_JSON_KEY }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}

  deploy-frontend:
    needs: build-frontend
    uses: ./.github/workflows/deploy-gcp.yaml
    with:
      container-name: frontend
      tag: latest
    secrets:
      GCP_CLOUDRUN_REGION: ${{ secrets.GCP_CLOUDRUN_REGION }}
      GAR_JSON_KEY: ${{ secrets.GAR_JSON_KEY }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
