name: Build and Push Frontend

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  call-build:
    uses: vivalareda/calculator-gpa/.github/workflows/reusable-docker-build.yaml@main
    with:
      container-name: frontend
      tag: latest
      context-path: frontend
      build-args: NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
    secrets:
      GCP_CLOUDRUN_REGION: ${{ secrets.GCP_CLOUDRUN_REGION }}
      GAR_JSON_KEY: ${{ secrets.GAR_JSON_KEY }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      NEXT_PUBLIC_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
